name: PR workflow
on: pull_request
jobs:
  build-images:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - name: Build and Push Images to local registry
        run: |
          set -x

          ./build-images.sh 